INSERT INTO `t_user` (`id`, `user_name`, `password`) VALUES (1, 'juggle', '24cb6bcbc65730e9650745d379613563');


INSERT INTO `t_domain` (`id`, `domain_code`, `domain_name`, `domain_desc`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'system_api', '系统示例接口', '这是系统内置的一个测试接口', '2023-06-06 22:44:13', NULL, '2024-03-10 22:08:29', NULL);


INSERT INTO `t_api` VALUES (1, 1, '登录接口', 'http://127.0.0.1:8686/example/user/login', '', 'POST', 'application/json', '2024-03-08 22:16:37', 1, '2024-03-10 23:17:55', NULL);
INSERT INTO `t_api` VALUES (2, 1, '获取用户信息', 'http://127.0.0.1:8686/example/user/getUserById', '获取用户信息-测试接口', 'GET', 'application/x-www-form-urlencoded', '2024-03-09 22:32:22', 1, '2024-03-10 23:21:16', 1);
INSERT INTO `t_api` VALUES (8, 1, '发布商品', 'http://127.0.0.1:8686/example/goods/releaseGoods', '', 'GET', 'application/json', '2024-03-10 22:28:57', 1, '2024-03-10 23:21:57', NULL);
INSERT INTO `t_api` VALUES (9, 1, '获取商品详情', 'http://127.0.0.1/example/goods/getGoodsInfo', '', 'GET', 'application/json', '2024-03-10 22:33:11', 1, '2024-03-10 23:22:37', NULL);
INSERT INTO `t_api` VALUES (15, 1, '购买商品', 'http://127.0.0.1:8686/example/order/placeOrder', '', 'POST', 'application/x-www-form-urlencoded', '2024-03-10 22:43:09', 1, '2024-03-10 23:23:39', NULL);
INSERT INTO `t_api` VALUES (16, 1, '获取订单列表', 'http://127.0.0.1:8686/example/order/getUserOrderList', '', 'GET', 'application/x-www-form-urlencoded', '2024-03-10 23:06:32', 1, '2024-03-10 23:24:03', 1);
INSERT INTO `t_api` VALUES (17, 1, '查询订单详情', 'http://127.0.0.1:8686/example/order/queryOrderByNo', '查询订单信息 -测试接口', 'GET', 'application/x-www-form-urlencoded', '2024-03-11 22:24:25', 1, '2024-03-10 23:24:27', 1);


INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'userName', '用户名', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 1, 'api', 1, '2024-03-10 22:16:37', NULL, '2024-03-10 23:17:49', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'password', '密码', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 1, 'api', 1, '2024-03-10 22:16:37', NULL, '2024-03-10 23:17:49', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'userId', '用户ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 1, '2024-03-10 22:15:37', NULL, '2024-03-10 23:16:49', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'userName', '用户名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 1, '2024-03-10 22:16:37', NULL, '2024-03-10 23:17:49', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'loginFlag', '是否登录成功', NULL, '{"type":"Boolean","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 1, '2024-03-10 22:16:37', NULL, '2024-03-10 23:17:44', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'orderNo', '订单号', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 1, 'api', 17, '2024-03-10 22:18:50', NULL, '2024-03-10 23:24:40', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'orderNo', '订单号', NULL, '{"type":"String","itemType":null,"structureSchema":null}', NULL, 'api', 17, '2024-03-10 22:18:50', NULL, '2024-03-10 23:24:40', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'userName', '订单名称', NULL, '{"type":"String","itemType":null,"structureSchema":null}', NULL, 'api', 17, '2024-03-10 22:18:50', NULL, '2024-03-10 23:24:40', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'userId	', '用户ID', NULL, '{"type":"Integer","itemType":null,"structureSchema":null}', NULL, 'api', 17, '2024-03-10 22:18:50', NULL, '2024-03-10 23:24:40', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'userId', '用户ID', NULL, '{"type":"Integer","itemType":null,"structureSchema":null}', 1, 'api', 2, '2024-03-10 22:20:20', NULL, '2024-03-10 23:21:31', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'id', '用户ID', NULL, '{"type":"Integer","itemType":null,"structureSchema":null}', NULL, 'api', 2, '2024-03-10 22:20:20', NULL, '2024-03-10 23:21:31', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'name', '用户姓名', NULL, '{"type":"String","itemType":null,"structureSchema":null}', NULL, 'api', 2, '2024-03-10 22:20:20', NULL, '2024-03-10 23:21:31', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'age', '用户年龄', NULL, '{"type":"Integer","itemType":null,"structureSchema":null}', NULL, 'api', 2, '2024-03-10 22:20:20', NULL, '2024-03-10 23:21:31', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'birthday', '用户生日', NULL, '{"type":"Date","itemType":null,"objectKey":null,"objectStructure":null}', NULL, 'api', 2, '2024-03-10 22:20:20', NULL, '2024-03-10 23:21:31', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'goodsName', '商品名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 0, 'api', 8, '2024-03-10 22:28:57', NULL, '2024-03-10 23:22:08', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'goodsInventory', '商品库存', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', 0, 'api', 8, '2024-03-10 22:28:57', NULL, '2024-03-10 23:22:08', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'goodsId', '商品ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 8, '2024-03-10 22:28:57', NULL, '2024-03-10 23:22:08', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'goodsName', '商品名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 8, '2024-03-10 22:28:57', NULL, '2024-03-10 23:22:08', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'goodsInventory', '商品库存', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 8, '2024-03-10 22:28:57', NULL, '2024-03-10 23:22:08', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'goodsName', '商品名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 1, 'api', 9, '2024-03-10 22:33:11', NULL, '2024-03-10 23:22:57', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'goodsInventory', '商品库存', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 0, 'api', 9, '2024-03-10 22:33:11', NULL, '2024-03-10 23:22:57', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'goodsId', '商品ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 9, '2024-03-10 22:33:11', NULL, '2024-03-10 23:22:58', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'goodsName', '商品名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 9, '2024-03-10 22:33:11', NULL, '2024-03-10 23:22:58', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'goodsPrice', '商品价格', NULL, '{"type":"Double","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 9, '2024-03-10 22:33:11', NULL, '2024-03-10 23:22:58', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'goodsInventory', '商品库存', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 9, '2024-03-10 22:33:11', NULL, '2024-03-10 23:22:58', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'orderName', '订单名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 0, 'api', 15, '2024-03-10 22:43:09', NULL, '2024-03-10 23:23:53', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'userId', '用户ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', 0, 'api', 15, '2024-03-10 22:43:09', NULL, '2024-03-10 23:23:53', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'orderNo', '订单号', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 15, '2024-03-10 22:43:09', NULL, '2024-03-10 23:23:53', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'orderName', '订单名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 15, '2024-03-10 22:43:09', NULL, '2024-03-10 23:23:53', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'userId', '用户ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 15, '2024-03-10 22:43:09', NULL, '2024-03-10 23:23:53', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'userId', '用户ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', 0, 'api', 16, '2024-03-10 23:14:33', NULL, '2024-03-10 23:24:18', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'orderName', '订单名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', 0, 'api', 16, '2024-03-10 23:14:33', NULL, '2024-03-10 23:24:18', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'userId', '用户ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'api', 16, '2024-03-10 23:14:33', NULL, '2024-03-10 23:24:18', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'orderList', '订单列表', NULL, '{"type":"List","itemType":"Object","objectKey":"orderDTO","objectStructure":"[{"propKey":"userId","propName":"用户ID","dataType":"{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}"},{"propKey":"orderName","propName":"订单名称","dataType":"{"type":"String","itemType":"","objectKey":null,"objectStructure":null}"},{"propKey":"orderNo","propName":"订单号","dataType":"{"type":"String","itemType":"","objectKey":null,"objectStructure":null}"}]"}', NULL, 'api', 16, '2024-03-10 23:14:33', NULL, '2024-03-10 23:24:18', NULL);


INSERT INTO `t_object` (`id`, `object_key`, `object_name`, `object_desc`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'orderDTO', '订单传输对象', '用于示例接口的对象', '2024-03-10 23:03:50', 1, NULL, NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (3, 'orderNo', '订单号', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'object', 1, '2024-03-10 23:03:51', NULL, '2024-03-10 23:48:59', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (3, 'orderName', '订单名称', NULL, '{"type":"String","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'object', 1, '2024-03-10 23:03:51', NULL, '2024-03-10 23:49:00', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `param_desc`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (3, 'userId', '用户ID', NULL, '{"type":"Integer","itemType":"","objectKey":null,"objectStructure":null}', NULL, 'object', 1, '2024-03-10 23:03:51', NULL, '2024-03-10 23:49:00', NULL);




INSERT INTO `t_flow_definition` (`id`, `flow_key`, `flow_name`, `flow_type`, `flow_content`, `remark`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'flow_sync', '同步示例流程', 'sync', '[{"key":"start_2s49s","name":"开始","elementType":"START","outgoings":["method_8w9r3"]},{"key":"method_8w9r3","name":"根据ID获取用户名称","elementType":"METHOD","desc":"这是了一个节点的描述","incomings":["start_2s49s"],"outgoings":["condition_83jd3"],"method":{"domainId":1,"methodId":1,"url":"http://127.0.0.1:8686/example/user/getUserById","requestType":"GET","requestContentType":"application/x-www-form-urlencoded","headerFillRules":[{"source":"input_id","sourceType":"VARIABLE","sourceDataType":"{"type":"Integer","itemType":null,"structureSchema":null}","target":"userId","targetType":"INPUT_PARAM","targetDataType":"{"type":"Integer","itemType":null,"structureSchema":null}"}],"inputFillRules":[{"source":"input_id","sourceType":"VARIABLE","sourceDataType":"{"type":"Integer","itemType":null,"structureSchema":null}","target":"userId","targetType":"INPUT_PARAM","targetDataType":"{"type":"Integer","itemType":null,"structureSchema":null}"}],"outputFillRules":[{"source":"name","sourceType":"OUTPUT_PARAM","sourceDataType":"{"type":"String","itemType":null,"structureSchema":null}","target":"output_userName","targetType":"VARIABLE","targetDataType":"{"type":"String","itemType":null,"structureSchema":null}"}]}},{"key":"condition_83jd3","name":"判断用户名称","elementType":"CONDITION","desc":null,"incomings":["method_8w9r3"],"outgoings":["end_5g463"],"conditions":[{"conditionName":"判断用户名称是否为zhansan","conditionType":"CUSTOM","outgoing":"end_5g463","expression":"input_name=="张三"||string.contains(input_name,''三'')","conditionExpressions":[[{"envKey":"input_name","dataType":"{"type":"String","itemType":null,"structureSchema":null}","operator":"equal","assignType":"constant","value":"张三"}],[{"envKey":"input_name","dataType":"{"type":"String","itemType":null,"structureSchema":null}","operator":"contains","assignType":"constant","value":"三"}]]},{"conditionName":"判断用户名称是否为lisi","conditionType":"CUSTOM","outgoing":"method_23s45","expression":"input_name=="lisi"","conditionExpressions":[[{"envKey":"input_name","dataType":"{"type":"String","itemType":null,"structureSchema":null}","operator":"equal","assignType":"constant","value":"lisi"}]]},{"conditionName":"默认else分支","conditionType":"DEFAULT","outgoing":"end_5g463","expression":null,"conditionExpressions":null}]},{"key":"method_23s45","name":"获取订单信息","elementType":"METHOD","desc":null,"incomings":["condition_83jd3"],"outgoings":["end_5g463"],"method":{"domainId":1,"methodId":2,"url":"http://127.0.0.1:8686/example/order/queryOrderByNo","requestType":"GET","requestContentType":null,"headerFillRules":null,"inputFillRules":null,"outputFillRules":null}},{"key":"end_5g463","name":"结束","elementType":"END","incomings":["condition_83jd3"]}]', NULL, NULL, NULL, '2024-03-07 00:10:02', NULL);
INSERT INTO `t_parameter` (`param_type`, `param_key`, `param_name`, `data_type`, `required`, `source_type`, `source_id`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 'userName', '流程出参-用户名称', '{"type":"String","itemType":null,"structureSchema":null}', NULL, 'flow', 1, NULL, NULL, NULL, NULL);
INSERT INTO `t_variable_info` (`id`, `flow_definition_id`, `env_key`, `env_name`, `env_type`, `data_type`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 1, 'input_id', '入参-用户ID变量', 1, '{"type":"Integer","itemType":"","structureSchema":""}', NULL, NULL, NULL, NULL);
INSERT INTO `t_variable_info` (`id`, `flow_definition_id`, `env_key`, `env_name`, `env_type`, `data_type`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (2, 1, 'input_name', '入参-用户姓名变量', 1, '{"type":"String","itemType":"","structureSchema":""}', NULL, NULL, NULL, NULL);
INSERT INTO `t_variable_info` (`id`, `flow_definition_id`, `env_key`, `env_name`, `env_type`, `data_type`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (3, 1, 'output_userName', '流程出参-用户姓名变量', 2, '{"type":"String","itemType":"","structureSchema":""}', NULL, NULL, NULL, NULL);

INSERT INTO `t_flow_info` (`id`, `flow_key`, `flow_name`, `flow_type`, `remark`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES (1, 'flow_sync', '测试同步流程', 'sync', '这是一个测试流程', NULL, NULL, NULL, NULL);
