export enum DrawerKey{
    EDIT_NODE_DRAWER = 'EDIT_NODE_DRAWER',
    DATA_SOURCE_DRAWER = 'DATA_SOURCE_DRAWER',
    OBJECT_DRAWER = 'OBJECT_DATA_DRAWER',
    API_DRAWER = 'API_DRAWER',
    FLOW_DEFINE_DRAWER = 'FLOW_DEFINE_DRAWER',
}